export const appAction = {
  TEST_PROMISE: 'TEST_PROMISE',
  TEST_PROMISE_SUCCESS: 'TEST_PROMISE_SUCCESS',
  TEST_PROMISE_FAILURE: 'TEST_PROMISE_FAILURE',
};

export const authAction = {
  IS_LOGIN_COMPONENT: 'IS_LOGIN_COMPONENT',
  IS_SIGNUP_COMPONENT: 'IS_SIGNUP_COMPONENT',

  ON_LOGIN: 'ON_LOGIN',
  ON_LOGIN_SUCCESS: 'ON_LOGIN_SUCCESS',

  LOAD_ACCESSTOKEN: 'LOAD_ACCESSTOKEN',
  LOAD_ACCESSTOKEN_SUCCESS: 'LOAD_ACCESSTOKEN_SUCCESS',
  LOAD_USERID: 'LOAD_USERID',
  LOAD_USERID_SUCCESS: 'LOAD_USERID_SUCCESS',

  ON_LOGOUT: 'ON_LOGOUT',
  ON_LOGOUT_SUCCESS: 'ON_LOGOUT_SUCCESS',
};

export const eventAction = {
  LOAD_EVENTS_LIST: 'LOAD_EVENTS_LIST',
  LOAD_EVENTS_LIST_SUCCESS: 'LOAD_EVENTS_LIST_SUCCESS',
};
