export const appAction = {
  TEST_PROMISE: 'TEST_PROMISE',
  TEST_PROMISE_SUCCESS: 'TEST_PROMISE_SUCCESS',
  TEST_PROMISE_FAILURE: 'TEST_PROMISE_FAILURE',
};

export const authAction = {
  IS_LOGIN_COMPONENT: 'IS_LOGIN_COMPONENT',
  IS_SIGNUP_COMPONENT: 'IS_SIGNUP_COMPONENT',

  ON_LOGIN: 'ON_LOGIN',
  ON_LOGIN_SUCCESS: 'ON_LOGIN_SUCCESS',

  LOAD_AUTH: 'LOAD_AUTH',
  LOAD_AUTH_SUCCESS: 'LOAD_AUTH_SUCCESS',

  ON_LOGOUT: 'ON_LOGOUT',
  ON_LOGOUT_SUCCESS: 'ON_LOGOUT_SUCCESS',
};
